
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |                                                                |
  |               -- ASP Ombudsman Information --                  |
  |                                                                |
  |  DynoTech Software is a member of the Association of Shareware |
  |  Professionals (ASP).  ASP wants to make sure that the         |
  |  shareware principle works for you.  If you are unable to      |
  |  resolve a shareware-related problem with an ASP member by     |
  |  contacting the member directly, ASP may be able to help.  The |
  |  ASP ombudsman can help you resolve a dispute or problem with  |
  |  an ASP member, but does not provide technical support for     |
  |  members' products.  Please write to the ASP Ombudsman at:     |
  |                                                                |
  |     ASP Ombudsman                  _______                     |
  |     545 Grover Road           ____|__     |                (R) |
  |     Muskegon, MI           --|       |    |------------------- |
  |        49442-9427 (USA)      |   ____|__  |  Association of    |
  |  send a Compuserve           |  |       |_|  Shareware         |
  |  message via CompuServe      |__|   o   |    Professionals     |
  |  mail to 70475,1071 or     -----|   |   |--------------------- |
  |  a FAX to 616-788-2765.         |___|___|    MEMBER            |
  |                                                                |
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
     If you have a question about a DynoTech product, write to:

         DynoTech Software
         1105 Home Avenue
         Waynesville, MO  65583-2231  USA

         FAX:  (573) 774-3052
         Technical Support:  (573) 336-3390

         CompuServe:  71373,572

         E-Mail:  DTGames@aol.com
                  dynotech@msn.com
